### PR TITLE
Unbreak on 0.6 by updating method definitions to new names

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by tkelman** [comment]
should these maybe define deprecations here for a little while?

**Comment by andreasnoack** [comment]
I've now deprecated them for the same period as the functions were deprecated in Julia. Then they should give warnings on 0.5 and people can adjust their packages.

**Comment by tkelman** [comment]
Whoops, this is broken - the depwarn isn't interpolating correctly, it's resulting in an UndefVarError at runtime.

**Comment by andreasnoack** [comment]
Do you see this in the tests of another package? I don't see anything in the tests here.

**Comment by tkelman** [comment]
yes, see JuliaWebAPI or Restful or others - http://pkg.julialang.org/pulse.html

the tests here aren't exercising the now-deprecated code paths

**Pull request merged**
