### PR TITLE
Add timeout option. Closes #16.

### LINKED ISSUE #16: "timeout" keyword
I'm blatantly and unapologetically stealing this from the python-requests library. Something like

```julia
get("http://github.com"; timeout=0.001)
```

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by quinnj** [comment]
I'm pretty sure we weren't passing our own tests here, so don't let those slow you down here. :)

**Comment by malmaud** [comment]
Indeed you were not :) This uses channels so it's not .3 compatible. Is that a concern?

**Comment by quinnj** [comment]
Hmmmm....maybe; is there a Compat for that?

**Comment by malmaud** [comment]
There is not.

**Comment by malmaud** [comment]
I updated it to work in both .3 and .4.

**Comment by quinnj** [comment]
+1

**Pull request merged**
