### PR TITLE
test travis separately on 0.4 and nightly

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by malmaud** [comment]
sweet testing action

**Comment by tkelman** [comment]
I heard you like tests. 32 bit is sad though https://ci.appveyor.com/project/malmaud/requests-jl/build/1.0.29/job/00mb6pywnt7qnlb2

**Comment by malmaud** [comment]
Seems like Zlib is triggering the failure.

**Comment by tkelman** [comment]
Just opened a PR

**Pull request merged**
