### PR TITLE
fix HttpParser #32

### PR DESCRIPTION
**Pull request by wildart**
This should fix [HttpParser #32](https://github.com/JuliaWeb/HttpParser.jl/issues/32).

### CODE REVIEW

**Comment by IainNZ** [comment]
Seems like test failure on 0.3 and 0.4?

**Comment by wildart** [comment]
It is unrelated to this PR. Investigating it.

**Comment by wildart** [comment]
For some reason multi-part post request to http://httpbin.org/post returns 400 Bad Request. I suspect bad multi-part encoding.

**Comment by malmaud** [comment]
I believe this is obsoleted now, but please correct me if I'm wrong.

**Pull request closed without merging**
