### PR TITLE
Add support for HTTP proxies

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by malmaud** [comment]
Closes https://github.com/JuliaWeb/Requests.jl/issues/80

**Comment by malmaud** [comment]
Care to take a look, @IainNZ?

**Comment by IainNZ** [comment]
Looks good, but I'm no expert

**Comment by malmaud** [comment]
Alright, I'll just merge then. I'm probably most excited about the experimental opt-in [Docker-based proxy test](https://github.com/JuliaWeb/Requests.jl/pull/81/files#diff-fce720c43af3c52c862fd7451c7374b8R221).

**Pull request merged**
